### PR TITLE
Redefine MetadataFile create ability to use ingest_metadata permissio…

### LINKED ISSUE #1505: Creating MetadataFile should require MetadataEditor role on collection in policy scope?
/cc @coblej @jt112

### PR DESCRIPTION
**Pull request by coblej**
…n on collection; closes #1505.

### CODE REVIEW

**Comment by dchandekstark** [comment]
+1

**Comment by coblej** [comment]
@dchandekstark In looking at this, it seems to me that https://github.com/duke-libraries/dul-hydra/blob/1505-metadata-file-authorization/spec/models/ability_spec.rb#L57:94 and https://github.com/duke-libraries/dul-hydra/blob/1505-metadata-file-authorization/spec/lib/dul_hydra/ability_definitions/metadata_file_ability_definitions_spec.rb basically duplicate one another.  Or are they somehow testing different things?  If they are essentially duplicates, I'm inclined to delete one or the other, in which case, do you have an opinion on which one should be kept?

**Comment by dchandekstark** [comment]
We should probably just test the ability definitions and remove any redundancy in the Ability tests.

**Comment by coblej** [comment]
@dchandekstark Will do that and resubmit.  Even though it's not directly related to the issue addressed by this pull request, I'll also move the METSFolder ability out of ability_spec to an appropriate ability definition test (which doesn't currently exist).

**Pull request merged**
