### PR TITLE
Reset the user/group selected upon granting a role without saving cha…

### LINKED ISSUE #1710: Role grant form does not reset properly
After using the "Grant Role" modal form once, the agent selector appears to remain on the previous selection, but in fact the selected value reverts to the default.

/cc @mikeadamo1

### PR DESCRIPTION
**Pull request by seanaery**
…nges. Also makes default agent unselected rather than Public. Fixes #1710

### CODE REVIEW

**Comment by dchandekstark** [comment]
You didn't mean to commit `config/locales/admin_set.yml`, right?  It's no longer used.

**Comment by seanaery** [comment]
@dchandekstark That's right, sorry. I'll amend this later tonight to exclude that file. Not sure how it got in there.

**Comment by seanaery** [comment]
@dchandekstark I've corrected the PR to only include the one revised file. 

Further documentation on the two lines of code I revised: 

- Select2 apparently expects the first option to be expressed as `<option></option>`. It selects the first on load by default; but it was previously interpreting "Public" as first, and failing to render the placeholder.
https://select2.github.io/options.html#my-first-option-is-being-displayed-instead-of-my-placeholder
https://github.com/select2/select2/issues/3939

- After a role is granted, I set the agent `select` value back to blank and triggered its change event to make Select2 update the text for the current select box. Some discussion of this approach here: http://stackoverflow.com/questions/17957040/reset-select2-value-and-show-placeholdler

**Comment by dchandekstark** [comment]
👍 Thanks, @seanaery !

**Pull request merged**
